// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user

import (
	"goFrameScaffold/api/user"
)

const A = 123

type ControllerV1 struct{}

func NewV1() user.IUserV1 {
	return &ControllerV1{}
}

// 自动生成
type ControllerV2 struct{}

func NewV2() user.IUserV2 {
	return &ControllerV2{}
}

const B = 123

// note: 使用 gf gen ctrl 命令自动生成时，往文件末尾追加代码，上面自己编写的代码不会被覆盖
type ControllerV3 struct{}

func NewV3() user.IUserV3 {
	return &ControllerV3{}
}
